/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  invoiceId?: string;
  invoiceUrl?: string;
  stripeCheckoutSessionId?: string;
  clerkUserId?: string;
  customerName?: string;
  email?: string;
  products?: Array<{
    productName?: string;
    price?: number;
    quantity?: number;
    _key: string;
  }>;
  totalPrice?: number;
  currency?: string;
  status?:
    "pending" | "processing" | "paid" | "shipped" | "delivered" | "cancelled";
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: AuthorReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  publishedAt?: string;
  isLatest?: boolean;
  body?: BlockContent;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }
>;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: string;
};

export type Address = {
  _id: string;
  _type: "address";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  city?: string;
  state?: string;
  zipCode?: string;
  isDefault?: boolean;
};

export type Brand = {
  _id: string;
  _type: "brand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  description?: string;
  price?: number;
  stock?: number;
  category?: CategoryReference;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Order
  | AuthorReference
  | SanityImageAssetReference
  | CategoryReference
  | Blog
  | BlockContent
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Author
  | Address
  | Brand
  | Product
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: ALL_PRODUCTS_QUERY
// Query: *[_type == "product" || _type == "products"] {    _id,    name,    "slug": slug.current,    price,    description,    stock,    "imageUrl": images[0].asset->url,    category-> {      title,      "slug": slug.current    }  }
export type ALL_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  price: number | null;
  description: string | null;
  stock: number | null;
  imageUrl: string | null;
  category: {
    title: string | null;
    slug: string | null;
  } | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: PRODUCT_BY_SLUG_QUERY
// Query: *[slug.current == $slug][0] {    _id,    _type,    name,    "slug": slug.current,    price,    description,    stock,    "imageUrl": images[0].asset->url,    "fallbackImageUrl": image.asset->url,     category-> {      title    }  }
export type PRODUCT_BY_SLUG_QUERY_RESULT =
  | {
      _id: string;
      _type: "address";
      name: string | null;
      slug: null;
      price: null;
      description: null;
      stock: null;
      imageUrl: null;
      fallbackImageUrl: null;
      category: null;
    }
  | {
      _id: string;
      _type: "author";
      name: string | null;
      slug: string | null;
      price: null;
      description: null;
      stock: null;
      imageUrl: null;
      fallbackImageUrl: string | null;
      category: null;
    }
  | {
      _id: string;
      _type: "blog";
      name: null;
      slug: string | null;
      price: null;
      description: null;
      stock: null;
      imageUrl: null;
      fallbackImageUrl: null;
      category: null;
    }
  | {
      _id: string;
      _type: "brand";
      name: null;
      slug: string | null;
      price: null;
      description: string | null;
      stock: null;
      imageUrl: null;
      fallbackImageUrl: string | null;
      category: null;
    }
  | {
      _id: string;
      _type: "category";
      name: null;
      slug: string | null;
      price: null;
      description: null;
      stock: null;
      imageUrl: null;
      fallbackImageUrl: string | null;
      category: null;
    }
  | {
      _id: string;
      _type: "order";
      name: null;
      slug: null;
      price: null;
      description: null;
      stock: null;
      imageUrl: null;
      fallbackImageUrl: null;
      category: null;
    }
  | {
      _id: string;
      _type: "product";
      name: string | null;
      slug: string | null;
      price: number | null;
      description: string | null;
      stock: number | null;
      imageUrl: string | null;
      fallbackImageUrl: null;
      category: {
        title: string | null;
      } | null;
    }
  | {
      _id: string;
      _type: "sanity.fileAsset";
      name: null;
      slug: null;
      price: null;
      description: string | null;
      stock: null;
      imageUrl: null;
      fallbackImageUrl: null;
      category: null;
    }
  | {
      _id: string;
      _type: "sanity.imageAsset";
      name: null;
      slug: null;
      price: null;
      description: string | null;
      stock: null;
      imageUrl: null;
      fallbackImageUrl: null;
      category: null;
    }
  | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "product" || _type == "products"] {\n    _id,\n    name,\n    "slug": slug.current,\n    price,\n    description,\n    stock,\n    "imageUrl": images[0].asset->url,\n    category-> {\n      title,\n      "slug": slug.current\n    }\n  }\n': ALL_PRODUCTS_QUERY_RESULT;
    '\n  *[slug.current == $slug][0] {\n    _id,\n    _type,\n    name,\n    "slug": slug.current,\n    price,\n    description,\n    stock,\n    "imageUrl": images[0].asset->url,\n    "fallbackImageUrl": image.asset->url, \n    category-> {\n      title\n    }\n  }\n': PRODUCT_BY_SLUG_QUERY_RESULT;
  }
}
