# helm/charts/next-js/templates/serviceaccount.yaml
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nextjs.serviceAccountName" . }}
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "nextjs.labels" . | nindent 4 }}
{{- end }}